version: '3.7'

services:
  rtimaintenancebot:
    image: rtimaintenancebot
    build: .
    environment:
      NODE_ENV: production
    volumes:
      - ./data:/data
      - ./src/commands:/src/commands
    networks:
      - RTIBot-network-prod
    container_name: RTIMaintenanceBot
networks:
  RTIBot-network-prod:
    external: true