# This is a basic workflow to help you get started with Actions

name: release-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [release]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs ssh commands
      - name: run script
        uses: fifsky/ssh-action@master
        with:
          command: |
            mv Config.json Config.json.backup
            git checkout release
            git pull
            mv Config.json.backup Config.json
            sh start.sh
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.RTIMAINTENANCEBOT_PRIVATE_OPENSSH_KEY }}
